### PR TITLE
Option to check and actively raise errors when waiting for objects conditions

### PR DESCRIPTION
**Pull request by piontec**
This PR renames and enhances `wait_for_namespaced_objects_condition` to allow for fail-fast on the first failed resource status. Implemented for App CRs.

### CODE REVIEW

**Comment by MarcelMue** [comment]
Can you give some context on where this is needed? 
We tried stuff like this in some golang libs previously but it turned tests very flaky. You might have intermittent error states which then fail the test. Chasing these down is super time consuming - so why ever check for them? IMO Kubernetes should be eventually be consistent and that is what we should test for.

Maybe there is a good reason I am not seeing :)

**Comment by piontec** [comment]
> Can you give some context on where this is needed? We tried stuff like this in some golang libs previously but it turned tests very flaky. You might have intermittent error states which then fail the test. Chasing these down is super time consuming - so why ever check for them? IMO Kubernetes should be eventually be consistent and that is what we should test for.
> 
> Maybe there is a good reason I am not seeing :)

The reason is to speed up testing - once an `App` gets into `failed` state, it won't get out of it on its own - so we prefer to fail the test early. This was already reported as an issue by few users. Still, I can see how this can be a problem in some rare use cases - it might be a good idea to add an option to opt-out of fail-fast error reporting for apps.

@rossf7 , can you PTAL here? How does it look like from the point of view of `app-operator`?

**Comment by rossf7** [comment]
> How does it look like from the point of view of app-operator?

@piontec app-operator and chart-operator will both retry so its possible an error happens that would get fixed later. Can we add a delay before failing rather than failing fast?

**Comment by piontec** [comment]
> > How does it look like from the point of view of app-operator?
> 
> @piontec app-operator and chart-operator will both retry so its possible an error happens that would get fixed later. Can we add a delay before failing rather than failing fast?

That's they way it worked before - there was a timeout to reach 'success' status. Thanks for the info Ross, I'll make it opt-in /out - I need to think about it for 1 min.

**Comment by piontec** [comment]
@rossf7 , @MarcelMue I made it opt-in to use the new fail-fast functionality.

**Review by rossf7 — APPROVED** [review]

**Pull request merged**
