### PR TITLE
added test_make_job_object to test_utils

### PR DESCRIPTION
**Pull request by JuriBog**

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Hi @JuriBog 

thanks for your contribution! Can you run fix the formatting issues on your code, then we can see if the tests actually work :)

**Comment by ubergesundheit** [comment]
Very nice,

if you would remove the unrelated changes in `docs` and  `.gitignore`, this would be ready to merge.

@piontec WDYT?

**Review by piontec — APPROVED** [review]
Looks good

**Review by ubergesundheit — APPROVED** [review]
LGTM

**Pull request merged**
